name: "Hello World Workflow"

# Controls when the action will run. Triggers the workflow on Push done to master or Production branch.
on: 
  push:
    branches: 
      - '**'
      

jobs: 
  hello_world: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Print Hello World"
        run: echo "Hello World"
        
      - name: "Print Hello Current Date"
        run: date

