name: "Multi Event Pilpeline / workflow"
on:
  push:
    branches:
        - master
        - test 
  schedule: 
       - cron: "0 10 * * 2,4"

  pull_request: # Event: Whenever a pull request is made to the repository
      branches:
          - master
      types:
          - .**.
        
  workflow_dispatch:


jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on Master Push"
              run: echo "Running on Master Push"

    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running On Pull Request"
    on-schedule: 
            if: github.event_name == 'schedule'
            run-on: ubuntu-latest
            steps: 
                - name: "Running on schedule"   # Step 1
                  run: echo "Running on schedule"
