name: "Multi Event Pilpeline / workflow"
on:
  push:
    branches:
        - master
        - test  


jobs:
    on-push:
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on Master Push"
              run: echo "Running on Master Push"          
 
